### ISSUE TITLE
Donkey car part 1 crashing

### ISSUE THREAD

**Issue by 0xrushi** [araffin/aae-train-donkeycar#6]
Hey Araffin,
I just came here from your [youtube video](https://www.youtube.com/watch?v=ngK33h00iBE&t=1s). Thanks for building that series :).
Is there any change in new packages?

```
root@breadpitt:~/rl-baselines3-zoo# python train.py --algo tqc --env donkey-mountain-track-v0 --eval-freq -1  --save-freq 20000
========== donkey-mountain-track-v0 ==========
Seed: 2242730085
Default hyperparameters for environment (ones being tuned will be overridden):
OrderedDict([('batch_size', 256),
             ('buffer_size', 10000),
             ('callback',
              [{'utils.callbacks.ParallelTrainCallback': {'gradient_steps': 200}}]),
             ('ent_coef', 'auto'),
             ('env_wrapper',
              [{'gym.wrappers.time_limit.TimeLimit': {'max_episode_steps': 10000}},
               {'utils.wrappers.HistoryWrapper': {'horizon': 2}}]),
             ('gamma', 0.99),
             ('gradient_steps', 256),
             ('learning_rate', 0.00073),
             ('n_timesteps', 2000000.0),
             ('normalize', "{'norm_obs': True, 'norm_reward': False}"),
             ('policy', 'CnnPolicy'),
             ('tau', 0.02),
             ('train_freq', 200)])
Using 1 environments
starting DonkeyGym env
Setting default: start_delay 5.0
Setting default: max_cte 8.0
Setting default: frame_skip 1
Setting default: cam_resolution (120, 160, 3)
Setting default: log_level 20
Setting default: host localhost
Setting default: port 9091
Setting default: steer_limit 1.0
Setting default: throttle_min 0.0
Setting default: throttle_max 1.0
INFO:gym_donkeycar.core.client:connecting to localhost:9091 
/opt/conda/lib/python3.7/site-packages/gym/spaces/box.py:74: UserWarning: WARN: Box bound precision lowered by casting to float32
  "Box bound precision lowered by casting to {}".format(self.dtype)
INFO:gym_donkeycar.envs.donkey_sim:on need car config
INFO:gym_donkeycar.envs.donkey_sim:sending car config.
INFO:gym_donkeycar.envs.donkey_sim:sim started!
Traceback (most recent call last):
  File "train.py", line 220, in <module>
    model = exp_manager.setup_experiment()
  File "/root/rl-baselines3-zoo/utils/exp_manager.py", line 173, in setup_experiment
    env = self.create_envs(n_envs, no_log=False)
  File "/root/rl-baselines3-zoo/utils/exp_manager.py", line 531, in create_envs
    monitor_kwargs=monitor_kwargs,
  File "/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/env_util.py", line 105, in make_vec_env
    return vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 25, in __init__
    self.envs = [fn() for fn in env_fns]
  File "/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 25, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/env_util.py", line 95, in _init
    env = wrapper_class(env, **wrapper_kwargs)
  File "/root/rl-baselines3-zoo/utils/utils.py", line 121, in wrap_env
    env = wrapper_class(env, **kwargs)
  File "/root/rl-baselines3-zoo/utils/wrappers.py", line 250, in __init__
    low = np.concatenate((low_obs, low_action))
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 1 dimension(s)


```

**Comment by 0xrushi** [comment]
Nevermind I found the issue, I had missed a line to comment in `tqc.yml`
Thanks
