### ISSUE TITLE
Using Trained AutoEncoder for Mountain track

### ISSUE THREAD

**Issue by jgamette** [araffin/aae-train-donkeycar#9]
Hello. I really appreciate your tutorials, but now I am a little lost. My goal is to simply just use the trained VAE for the mountain track and have the agent start learning on the mountain track. I believe I have most of the packages downloaded, but could you please guide me in the right direction on how to do this? Thank you so much

**Comment by jgamette** [comment]
Hello. I have currently done everything listed so far in the tutorials. When I run the code, it says there is no module named wandb. Is this because I didn't use pip install -r requirements.txt after cloning rl-baselines3-zoo? or is there another reason. I have used the pip install -e . on the feats that I have supposed to do, but the requirements.txt of rl-baselines3-zoo were not installed in the video, so I figured it was not needed. Thank you

**Comment by jgamette** [comment]
Below is the error I get when trying to install requirements of rl-baselines3-zoo:

Collecting gym==0.21 (from -r requirements.txt (line 1))
  Using cached gym-0.21.0.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by araffin** [comment]
https://github.com/openai/gym/issues/3176#issuecomment-1560026649

**Comment by jgamette** [comment]
Thank you. I think that what you did worked. I ran into another error regarding my environment?

Traceback (most recent call last):
  File "train.py", line 260, in <module>
    results = exp_manager.setup_experiment()
  File "C:\Users\james\OneDrive\Documents\TQCFinal\final\rl-baselines3-zoo\utils\exp_manager.py", line 181, in setup_experiment
    env = self.create_envs(n_envs, no_log=False)
  File "C:\Users\james\OneDrive\Documents\TQCFinal\final\rl-baselines3-zoo\utils\exp_manager.py", line 540, in create_envs
    env = make_vec_env(
  File "C:\Users\james\anaconda3\envs\JAMESFINAL\lib\site-packages\stable_baselines3\common\env_util.py", line 125, in make_vec_env
    vec_env = vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
  File "C:\Users\james\anaconda3\envs\JAMESFINAL\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 30, in __init__
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "C:\Users\james\anaconda3\envs\JAMESFINAL\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 30, in <listcomp>
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "C:\Users\james\anaconda3\envs\JAMESFINAL\lib\site-packages\stable_baselines3\common\env_util.py", line 94, in _init
    env = gym.make(env_id, **kwargs)  # type: ignore[arg-type]
  File "C:\Users\james\anaconda3\envs\JAMESFINAL\lib\site-packages\gymnasium\envs\registration.py", line 741, in make
    env_spec = _find_spec(id)
  File "C:\Users\james\anaconda3\envs\JAMESFINAL\lib\site-packages\gymnasium\envs\registration.py", line 527, in _find_spec
    _check_version_exists(ns, name, version)
  File "C:\Users\james\anaconda3\envs\JAMESFINAL\lib\site-packages\gymnasium\envs\registration.py", line 393, in _check_version_exists
    _check_name_exists(ns, name)
  File "C:\Users\james\anaconda3\envs\JAMESFINAL\lib\site-packages\gymnasium\envs\registration.py", line 370, in _check_name_exists
    raise error.NameNotFound(
gymnasium.error.NameNotFound: Environment `donkey-mountain-track` doesn't exist.

I am using an anaconda env, and open up a terminal through that env to get the correct Python version. Is there something I missed regarding setting up an environment? I didn't realize it would go through the code of the anaconda env. Thanks for your help!
